routes:
  /sitemap:
    template: sitemap
    layout: sitemap
    content_type: xml
  /search: search
  /users: user/index
  /users/{username}: user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
collections: [ ]
taxonomies: [ ]
